# Rest-client stöder .env
#@API_URL = {{$dotenv PRODUCTION_API}}
@API_URL = http://localhost:3001

@DEV_TOKEN = {{$dotenv DEV_TOKEN}} 

GET {{API_URL}}/notes

### GET single note
GET {{API_URL}}/notes/7
Authorization: Bearer {{DEV_TOKEN}}

### Skapa ny note
POST {{API_URL}}/notes
Content-Type: application/json
Authorization: Bearer {{DEV_TOKEN}}

{
    "author_id": 2,
    "note": "någon annans note"
}

### Uppdatera note
PUT {{API_URL}}/notes/2
Content-Type: application/json

{
    "note": "Ny text!!"
}

### Uppdatera note
DELETE {{API_URL}}/notes/4
