services:
  node-app:
    build:
      context: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      # local:remote  (lokal-dator:container)
      - "3001:3000"
    environment:
      # lägg hit ENV-variabler som containern ska se
      - MODE
      - DATABASE_URL
      - JWT_SECRET
